FROM python:3.7-alpine
WORKDIR /code
COPY requirements.txt requirements.txt
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install -r requirements.txt
COPY . .
CMD ["python","con.py"]
CMD ["sh"]
